# Generated by Django 4.0.3 on 2022-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('registration_number', models.CharField(max_length=8, verbose_name='Registration number')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('email', models.EmailField(max_length=32)),
            ],
        ),
    ]
