# Generated by Django 4.0.3 on 2022-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=8, unique=True, verbose_name='Registration number'),
        ),
    ]
